import type { Hospital, ProvinceData } from "./types";

export const filterOptions = {
  region: [
    { label: "全国", value: "all" },
    { label: "华北", value: "huabei" },
    { label: "华东", value: "huadong" },
    { label: "华南", value: "huanan" },
    { label: "华中", value: "huazhong" },
    { label: "西南", value: "xinan" },
    { label: "西北", value: "xibei" },
    { label: "东北", value: "dongbei" },
  ],
  hospitalLevel: [
    { label: "全部", value: "all" },
    { label: "三级甲等", value: "sanjiayi" },
    { label: "三级乙等", value: "sanjiyi" },
    { label: "二级甲等", value: "erjiayi" },
    { label: "二级乙等", value: "erjiyi" },
    { label: "一级", value: "yiji" },
  ],
  hospitalType: [
    { label: "全部", value: "all" },
    { label: "综合医院", value: "zonghe" },
    { label: "专科医院", value: "zhuanke" },
    { label: "中医医院", value: "zhongyi" },
    { label: "妇幼保健院", value: "fuyou" },
  ],
  deviceCategory: [
    { label: "全部", value: "all" },
    { label: "生化分析仪", value: "biochem" },
    { label: "免疫分析仪", value: "immuno" },
    { label: "血液分析仪", value: "hematology" },
    { label: "凝血分析仪", value: "coag" },
    { label: "尿沉渣分析仪", value: "urine" },
  ],
  deviceModel: [
    { label: "全部", value: "all" },
    { label: "BS-2000M", value: "bs2000m" },
    { label: "BS-2200", value: "bs2200" },
    { label: "CL-8000", value: "cl8000" },
    { label: "CL-6000", value: "cl6000" },
    { label: "BC-7500", value: "bc7500" },
    { label: "BC-6800", value: "bc6800" },
  ],
};

// 按省份分组的医院数量（用于地图展示）
export const provinceMapData: ProvinceData[] = [
  { name: "北京市", value: 24 },
  { name: "天津市", value: 12 },
  { name: "河北省", value: 35 },
  { name: "山西省", value: 18 },
  { name: "内蒙古自治区", value: 10 },
  { name: "辽宁省", value: 22 },
  { name: "吉林省", value: 14 },
  { name: "黑龙江省", value: 16 },
  { name: "上海市", value: 28 },
  { name: "江苏省", value: 42 },
  { name: "浙江省", value: 38 },
  { name: "安徽省", value: 20 },
  { name: "福建省", value: 25 },
  { name: "江西省", value: 18 },
  { name: "山东省", value: 40 },
  { name: "河南省", value: 30 },
  { name: "湖北省", value: 26 },
  { name: "湖南省", value: 22 },
  { name: "广东省", value: 48 },
  { name: "广西壮族自治区", value: 16 },
  { name: "海南省", value: 8 },
  { name: "重庆市", value: 15 },
  { name: "四川省", value: 32 },
  { name: "贵州省", value: 12 },
  { name: "云南省", value: 14 },
  { name: "西藏自治区", value: 3 },
  { name: "陕西省", value: 18 },
  { name: "甘肃省", value: 10 },
  { name: "青海省", value: 5 },
  { name: "宁夏回族自治区", value: 6 },
  { name: "新疆维吾尔自治区", value: 8 },
  { name: "台湾省", value: 0 },
  { name: "香港特别行政区", value: 0 },
  { name: "澳门特别行政区", value: 0 },
];

// 固定的 Mock 医院数据（不使用 Math.random，避免 SSR/CSR Hydration Mismatch）
export const mockHospitals: Hospital[] = [
  { id: "h1", name: "东城区人民医院", province: "北京市", city: "东城区", level: "三级甲等", type: "综合医院", deviceCount: 5, deviceModels: ["BS-2000M", "CL-8000", "BC-7500"], status: "active" },
  { id: "h2", name: "西城区中心医院", province: "北京市", city: "西城区", level: "三级甲等", type: "综合医院", deviceCount: 3, deviceModels: ["BS-2200", "CL-6000"], status: "active" },
  { id: "h3", name: "朝阳区第一人民医院", province: "北京市", city: "朝阳区", level: "三级乙等", type: "综合医院", deviceCount: 6, deviceModels: ["BS-2000M", "CL-8000", "BC-6800", "BC-7500"], status: "active" },
  { id: "h4", name: "海淀区中西医结合医院", province: "北京市", city: "海淀区", level: "二级甲等", type: "专科医院", deviceCount: 2, deviceModels: ["CL-6000"], status: "pending" },

  { id: "h5", name: "黄浦区人民医院", province: "上海市", city: "黄浦区", level: "三级甲等", type: "综合医院", deviceCount: 4, deviceModels: ["BS-2000M", "CL-8000"], status: "active" },
  { id: "h6", name: "徐汇区中心医院", province: "上海市", city: "徐汇区", level: "三级甲等", type: "综合医院", deviceCount: 7, deviceModels: ["BS-2000M", "BS-2200", "CL-8000", "BC-7500"], status: "active" },
  { id: "h7", name: "浦东新区第一人民医院", province: "上海市", city: "浦东新区", level: "三级甲等", type: "综合医院", deviceCount: 5, deviceModels: ["CL-8000", "BC-6800", "BC-7500"], status: "active" },
  { id: "h8", name: "静安区中医院", province: "上海市", city: "静安区", level: "二级甲等", type: "中医医院", deviceCount: 1, deviceModels: ["CL-6000"], status: "inactive" },

  { id: "h9", name: "广州人民医院", province: "广东省", city: "广州", level: "三级甲等", type: "综合医院", deviceCount: 6, deviceModels: ["BS-2000M", "CL-8000", "BC-7500"], status: "active" },
  { id: "h10", name: "深圳中心医院", province: "广东省", city: "深圳", level: "三级甲等", type: "综合医院", deviceCount: 8, deviceModels: ["BS-2000M", "BS-2200", "CL-8000", "CL-6000", "BC-6800"], status: "active" },
  { id: "h11", name: "东莞第一人民医院", province: "广东省", city: "东莞", level: "二级甲等", type: "综合医院", deviceCount: 3, deviceModels: ["BS-2200", "CL-6000"], status: "pending" },
  { id: "h12", name: "佛山中医院", province: "广东省", city: "佛山", level: "二级甲等", type: "中医医院", deviceCount: 2, deviceModels: ["BC-6800"], status: "active" },

  { id: "h13", name: "南京人民医院", province: "江苏省", city: "南京", level: "三级甲等", type: "综合医院", deviceCount: 5, deviceModels: ["BS-2000M", "CL-8000", "BC-7500"], status: "active" },
  { id: "h14", name: "苏州中心医院", province: "江苏省", city: "苏州", level: "三级甲等", type: "综合医院", deviceCount: 4, deviceModels: ["CL-8000", "BC-6800"], status: "active" },
  { id: "h15", name: "无锡第一人民医院", province: "江苏省", city: "无锡", level: "三级乙等", type: "综合医院", deviceCount: 3, deviceModels: ["BS-2200", "CL-6000"], status: "active" },
  { id: "h16", name: "常州妇幼保健院", province: "江苏省", city: "常州", level: "二级甲等", type: "妇幼保健院", deviceCount: 2, deviceModels: ["BC-7500"], status: "pending" },

  { id: "h17", name: "杭州人民医院", province: "浙江省", city: "杭州", level: "三级甲等", type: "综合医院", deviceCount: 6, deviceModels: ["BS-2000M", "CL-8000", "BC-7500"], status: "active" },
  { id: "h18", name: "宁波中心医院", province: "浙江省", city: "宁波", level: "三级甲等", type: "综合医院", deviceCount: 4, deviceModels: ["CL-8000", "BC-6800"], status: "active" },
  { id: "h19", name: "温州第一人民医院", province: "浙江省", city: "温州", level: "三级乙等", type: "综合医院", deviceCount: 3, deviceModels: ["BS-2200"], status: "active" },
  { id: "h20", name: "绍兴中医院", province: "浙江省", city: "绍兴", level: "二级甲等", type: "中医医院", deviceCount: 1, deviceModels: ["CL-6000"], status: "inactive" },

  { id: "h21", name: "济南人民医院", province: "山东省", city: "济南", level: "三级甲等", type: "综合医院", deviceCount: 5, deviceModels: ["BS-2000M", "CL-8000"], status: "active" },
  { id: "h22", name: "青岛中心医院", province: "山东省", city: "青岛", level: "三级甲等", type: "综合医院", deviceCount: 7, deviceModels: ["BS-2000M", "BS-2200", "CL-8000", "BC-7500"], status: "active" },
  { id: "h23", name: "烟台第一人民医院", province: "山东省", city: "烟台", level: "二级甲等", type: "综合医院", deviceCount: 2, deviceModels: ["CL-6000"], status: "pending" },
  { id: "h24", name: "潍坊中医院", province: "山东省", city: "潍坊", level: "二级乙等", type: "中医医院", deviceCount: 1, deviceModels: ["BC-6800"], status: "inactive" },

  { id: "h25", name: "成都人民医院", province: "四川省", city: "成都", level: "三级甲等", type: "综合医院", deviceCount: 6, deviceModels: ["BS-2000M", "CL-8000", "BC-7500"], status: "active" },
  { id: "h26", name: "绵阳中心医院", province: "四川省", city: "绵阳", level: "三级乙等", type: "综合医院", deviceCount: 3, deviceModels: ["BS-2200", "CL-6000"], status: "active" },
  { id: "h27", name: "德阳第一人民医院", province: "四川省", city: "德阳", level: "二级甲等", type: "综合医院", deviceCount: 2, deviceModels: ["BC-6800"], status: "pending" },
  { id: "h28", name: "宜宾中医院", province: "四川省", city: "宜宾", level: "二级甲等", type: "中医医院", deviceCount: 1, deviceModels: ["CL-6000"], status: "inactive" },

  { id: "h29", name: "郑州人民医院", province: "河南省", city: "郑州", level: "三级甲等", type: "综合医院", deviceCount: 5, deviceModels: ["BS-2000M", "CL-8000"], status: "active" },
  { id: "h30", name: "洛阳中心医院", province: "河南省", city: "洛阳", level: "三级乙等", type: "综合医院", deviceCount: 4, deviceModels: ["BS-2200", "CL-8000", "BC-6800"], status: "active" },
  { id: "h31", name: "开封第一人民医院", province: "河南省", city: "开封", level: "二级甲等", type: "综合医院", deviceCount: 2, deviceModels: ["CL-6000"], status: "pending" },
  { id: "h32", name: "新乡妇幼保健院", province: "河南省", city: "新乡", level: "二级甲等", type: "妇幼保健院", deviceCount: 1, deviceModels: ["BC-7500"], status: "inactive" },

  { id: "h33", name: "武汉人民医院", province: "湖北省", city: "武汉", level: "三级甲等", type: "综合医院", deviceCount: 8, deviceModels: ["BS-2000M", "BS-2200", "CL-8000", "CL-6000", "BC-6800"], status: "active" },
  { id: "h34", name: "宜昌中心医院", province: "湖北省", city: "宜昌", level: "三级乙等", type: "综合医院", deviceCount: 3, deviceModels: ["BS-2200", "CL-6000"], status: "active" },
  { id: "h35", name: "襄阳第一人民医院", province: "湖北省", city: "襄阳", level: "二级甲等", type: "综合医院", deviceCount: 2, deviceModels: ["BC-6800"], status: "pending" },
  { id: "h36", name: "荆州中医院", province: "湖北省", city: "荆州", level: "二级乙等", type: "中医医院", deviceCount: 1, deviceModels: ["CL-6000"], status: "inactive" },

  { id: "h37", name: "长沙人民医院", province: "湖南省", city: "长沙", level: "三级甲等", type: "综合医院", deviceCount: 5, deviceModels: ["BS-2000M", "CL-8000", "BC-7500"], status: "active" },
  { id: "h38", name: "株洲中心医院", province: "湖南省", city: "株洲", level: "三级乙等", type: "综合医院", deviceCount: 3, deviceModels: ["BS-2200", "CL-6000"], status: "active" },
  { id: "h39", name: "湘潭第一人民医院", province: "湖南省", city: "湘潭", level: "二级甲等", type: "综合医院", deviceCount: 2, deviceModels: ["BC-6800"], status: "pending" },
  { id: "h40", name: "衡阳中医院", province: "湖南省", city: "衡阳", level: "二级乙等", type: "中医医院", deviceCount: 1, deviceModels: ["CL-6000"], status: "inactive" },

  { id: "h41", name: "福州人民医院", province: "福建省", city: "福州", level: "三级甲等", type: "综合医院", deviceCount: 4, deviceModels: ["BS-2000M", "CL-8000"], status: "active" },
  { id: "h42", name: "厦门中心医院", province: "福建省", city: "厦门", level: "三级甲等", type: "综合医院", deviceCount: 6, deviceModels: ["BS-2000M", "CL-8000", "BC-7500", "BC-6800"], status: "active" },
  { id: "h43", name: "泉州第一人民医院", province: "福建省", city: "泉州", level: "二级甲等", type: "综合医院", deviceCount: 2, deviceModels: ["CL-6000"], status: "pending" },
  { id: "h44", name: "漳州妇幼保健院", province: "福建省", city: "漳州", level: "二级甲等", type: "妇幼保健院", deviceCount: 1, deviceModels: ["BC-7500"], status: "inactive" },

  { id: "h45", name: "合肥人民医院", province: "安徽省", city: "合肥", level: "三级甲等", type: "综合医院", deviceCount: 5, deviceModels: ["BS-2000M", "CL-8000", "BC-7500"], status: "active" },
  { id: "h46", name: "芜湖中心医院", province: "安徽省", city: "芜湖", level: "三级乙等", type: "综合医院", deviceCount: 3, deviceModels: ["BS-2200", "CL-6000"], status: "active" },
  { id: "h47", name: "蚌埠第一人民医院", province: "安徽省", city: "蚌埠", level: "二级甲等", type: "综合医院", deviceCount: 2, deviceModels: ["BC-6800"], status: "pending" },
  { id: "h48", name: "安庆中医院", province: "安徽省", city: "安庆", level: "二级乙等", type: "中医医院", deviceCount: 1, deviceModels: ["CL-6000"], status: "inactive" },

  { id: "h49", name: "南昌人民医院", province: "江西省", city: "南昌", level: "三级甲等", type: "综合医院", deviceCount: 4, deviceModels: ["BS-2000M", "CL-8000"], status: "active" },
  { id: "h50", name: "上饶中心医院", province: "江西省", city: "上饶", level: "三级乙等", type: "综合医院", deviceCount: 3, deviceModels: ["BS-2200", "CL-6000"], status: "active" },
  { id: "h51", name: "九江第一人民医院", province: "江西省", city: "九江", level: "二级甲等", type: "综合医院", deviceCount: 2, deviceModels: ["BC-6800"], status: "pending" },
  { id: "h52", name: "赣州妇幼保健院", province: "江西省", city: "赣州", level: "二级甲等", type: "妇幼保健院", deviceCount: 1, deviceModels: ["BC-7500"], status: "inactive" },

  { id: "h53", name: "沈阳人民医院", province: "辽宁省", city: "沈阳", level: "三级甲等", type: "综合医院", deviceCount: 6, deviceModels: ["BS-2000M", "CL-8000", "BC-7500"], status: "active" },
  { id: "h54", name: "大连中心医院", province: "辽宁省", city: "大连", level: "三级甲等", type: "综合医院", deviceCount: 5, deviceModels: ["BS-2200", "CL-8000", "BC-6800"], status: "active" },
  { id: "h55", name: "鞍山第一人民医院", province: "辽宁省", city: "鞍山", level: "二级甲等", type: "综合医院", deviceCount: 2, deviceModels: ["CL-6000"], status: "pending" },
  { id: "h56", name: "锦州中医院", province: "辽宁省", city: "锦州", level: "二级乙等", type: "中医医院", deviceCount: 1, deviceModels: ["BC-6800"], status: "inactive" },

  { id: "h57", name: "西安人民医院", province: "陕西省", city: "西安", level: "三级甲等", type: "综合医院", deviceCount: 5, deviceModels: ["BS-2000M", "CL-8000", "BC-7500"], status: "active" },
  { id: "h58", name: "宝鸡中心医院", province: "陕西省", city: "宝鸡", level: "三级乙等", type: "综合医院", deviceCount: 3, deviceModels: ["BS-2200", "CL-6000"], status: "active" },
  { id: "h59", name: "咸阳第一人民医院", province: "陕西省", city: "咸阳", level: "二级甲等", type: "综合医院", deviceCount: 2, deviceModels: ["BC-6800"], status: "pending" },
  { id: "h60", name: "渭南中医院", province: "陕西省", city: "渭南", level: "二级乙等", type: "中医医院", deviceCount: 1, deviceModels: ["CL-6000"], status: "inactive" },

  { id: "h61", name: "渝中区人民医院", province: "重庆市", city: "渝中区", level: "三级甲等", type: "综合医院", deviceCount: 4, deviceModels: ["BS-2000M", "CL-8000"], status: "active" },
  { id: "h62", name: "江北区中心医院", province: "重庆市", city: "江北区", level: "三级乙等", type: "综合医院", deviceCount: 3, deviceModels: ["BS-2200", "CL-6000"], status: "active" },
  { id: "h63", name: "沙坪坝区第一人民医院", province: "重庆市", city: "沙坪坝区", level: "二级甲等", type: "综合医院", deviceCount: 2, deviceModels: ["BC-6800"], status: "pending" },
  { id: "h64", name: "渝北区中医院", province: "重庆市", city: "渝北区", level: "二级乙等", type: "中医医院", deviceCount: 1, deviceModels: ["CL-6000"], status: "inactive" },

  { id: "h65", name: "石家庄人民医院", province: "河北省", city: "石家庄", level: "三级甲等", type: "综合医院", deviceCount: 5, deviceModels: ["BS-2000M", "CL-8000", "BC-7500"], status: "active" },
  { id: "h66", name: "唐山中心医院", province: "河北省", city: "唐山", level: "三级乙等", type: "综合医院", deviceCount: 3, deviceModels: ["BS-2200", "CL-6000"], status: "active" },
  { id: "h67", name: "保定第一人民医院", province: "河北省", city: "保定", level: "二级甲等", type: "综合医院", deviceCount: 2, deviceModels: ["BC-6800"], status: "pending" },
  { id: "h68", name: "邯郸中医院", province: "河北省", city: "邯郸", level: "二级乙等", type: "中医医院", deviceCount: 1, deviceModels: ["CL-6000"], status: "inactive" },

  { id: "h69", name: "太原人民医院", province: "山西省", city: "太原", level: "三级甲等", type: "综合医院", deviceCount: 4, deviceModels: ["BS-2000M", "CL-8000"], status: "active" },
  { id: "h70", name: "大同中心医院", province: "山西省", city: "大同", level: "三级乙等", type: "综合医院", deviceCount: 3, deviceModels: ["BS-2200", "CL-6000"], status: "active" },
  { id: "h71", name: "运城第一人民医院", province: "山西省", city: "运城", level: "二级甲等", type: "综合医院", deviceCount: 2, deviceModels: ["BC-6800"], status: "pending" },
  { id: "h72", name: "临汾中医院", province: "山西省", city: "临汾", level: "二级乙等", type: "中医医院", deviceCount: 1, deviceModels: ["CL-6000"], status: "inactive" },

  { id: "h73", name: "昆明人民医院", province: "云南省", city: "昆明", level: "三级甲等", type: "综合医院", deviceCount: 5, deviceModels: ["BS-2000M", "CL-8000", "BC-7500"], status: "active" },
  { id: "h74", name: "曲靖中心医院", province: "云南省", city: "曲靖", level: "三级乙等", type: "综合医院", deviceCount: 3, deviceModels: ["BS-2200", "CL-6000"], status: "active" },
  { id: "h75", name: "大理第一人民医院", province: "云南省", city: "大理", level: "二级甲等", type: "综合医院", deviceCount: 2, deviceModels: ["BC-6800"], status: "pending" },
  { id: "h76", name: "红河中医院", province: "云南省", city: "红河", level: "二级乙等", type: "中医医院", deviceCount: 1, deviceModels: ["CL-6000"], status: "inactive" },

  { id: "h77", name: "南宁人民医院", province: "广西壮族自治区", city: "南宁", level: "三级甲等", type: "综合医院", deviceCount: 4, deviceModels: ["BS-2000M", "CL-8000"], status: "active" },
  { id: "h78", name: "柳州中心医院", province: "广西壮族自治区", city: "柳州", level: "三级乙等", type: "综合医院", deviceCount: 3, deviceModels: ["BS-2200", "CL-6000"], status: "active" },
  { id: "h79", name: "桂林第一人民医院", province: "广西壮族自治区", city: "桂林", level: "二级甲等", type: "综合医院", deviceCount: 2, deviceModels: ["BC-6800"], status: "pending" },
  { id: "h80", name: "梧州妇幼保健院", province: "广西壮族自治区", city: "梧州", level: "二级甲等", type: "妇幼保健院", deviceCount: 1, deviceModels: ["BC-7500"], status: "inactive" },
];
