export const filterOptions = {
  region: [
    { label: "全国", value: "all" },
    { label: "华北", value: "huabei" },
    { label: "华东", value: "huadong" },
    { label: "华南", value: "huanan" },
    { label: "华中", value: "huazhong" },
    { label: "西南", value: "xinan" },
    { label: "西北", value: "xibei" },
    { label: "东北", value: "dongbei" },
  ],
  hospitalLevel: [
    { label: "全部", value: "all" },
    { label: "三级甲等", value: "sanjiayi" },
    { label: "三级乙等", value: "sanjiyi" },
    { label: "二级甲等", value: "erjiayi" },
    { label: "二级乙等", value: "erjiyi" },
    { label: "一级", value: "yiji" },
  ],
  hospitalType: [
    { label: "全部", value: "all" },
    { label: "综合医院", value: "zonghe" },
    { label: "专科医院", value: "zhuanke" },
    { label: "中医医院", value: "zhongyi" },
    { label: "妇幼保健院", value: "fuyou" },
  ],
  deviceCategory: [
    { label: "全部", value: "all" },
    { label: "生化分析仪", value: "biochem" },
    { label: "免疫分析仪", value: "immuno" },
    { label: "血液分析仪", value: "hematology" },
    { label: "凝血分析仪", value: "coag" },
    { label: "尿沉渣分析仪", value: "urine" },
  ],
  deviceModel: [
    { label: "全部", value: "all" },
    { label: "BS-2000M", value: "bs2000m" },
    { label: "BS-2200", value: "bs2200" },
    { label: "CL-8000", value: "cl8000" },
    { label: "CL-6000", value: "cl6000" },
    { label: "BC-7500", value: "bc7500" },
    { label: "BC-6800", value: "bc6800" },
  ],
};
